%% store paths to data directories and copy necessary files
% before this runs you need to copy the regsiter.dat file form
% FreesurferSegmentations/subject/labels to
% FreesurferSegmentations/subject/surf

anat_ids = {'siobhan' 'avt' 'anthony_new_recon_2017'...
    'kalanit_new_recon_2017' 'mareike' 'jesse_new_recon_2017'...
    'brianna' 'swaroop' 'eshed'...
    'richard' 'cody' 'marisa'...
    'kari' 'alexis' 'nathan'...
    'dawn' 'erica' 'th'...
    'ek' 'gm' 'bl'...
    'mw' 'jk' 'pe'...
    'ie' 'pw' 'ks' ...
    'mz' 'mm' 'ans'};

fs_ids = {'siobhan' 'avt' 'anthony_new_recon_2017'...
    'kalanit_new_recon_2017' 'mareike' 'jesse_new_recon_2017'...
    'brianna' 'swaroop' 'eshed'...
    'richard' 'cody' 'marisa'...
    'kari' 'alexis' 'nathan'...
    'dawn' 'erica' 'th'...
    'ek' 'gm' 'bl'...
    'mw' 'jk' 'pe'...
    'ie' 'pw' 'ks' ...
    'mz' 'mm' 'ans'};

RAID=['/sni-storage/kalanit/biac2/kgs'];

fsa_dir = fullfile(RAID, '3Danat', 'FreesurferSegmentations', 'fsaverage-bkup');

map_name = {'02_reading_vs_all_lh_proj_max'};

%average surface maps across all sessions
outdir=fullfile('/share/kalanit/biac2/kgs/projects/PredictFuncFromStruct/data4Predict/fsaverageSpace');
cd(outdir);

allSubjects=1:30
for ss = allSubjects
    subjects=allSubjects(allSubjects~=ss)
    
    searchFor=strcat('Subject*',map_name{:},'*');
    all_inputs=dir(searchFor);
    leave1out=strcat('Subject_',num2str(ss),'_',map_name{:},'.mgh');
    
    for i=1:length(all_inputs)-1
        if strcmp(all_inputs(i).name,leave1out)
            all_inputs(i)=[];
        end
    end
    
    inputs=strcat({all_inputs(:).name},{' '});
    
    unix(['mri_concat --i ' horzcat(inputs{:}) '--o ' ...
        strcat('Group_',map_name{:}, '_without_Subject_', num2str(ss), '.mgh') ' --mean']); % left hemi
end
