%% store paths to data directories and copy necessary files
% before this runs you need to copy the regsiter.dat file form
% FreesurferSegmentations/subject/labels to
% FreesurferSegmentations/subject/surf


anat_ids = {'siobhan' 'avt' 'anthony_new_recon_2017'...
    'kalanit_new_recon_2017' 'mareike' 'jesse_new_recon_2017'...
    'brianna' 'swaroop' 'eshed'...
    'richard' 'cody' 'marisa'...
    'kari' 'alexis' 'nathan'...
    'dawn' 'erica' 'th'...
    'ek' 'gm' 'bl'...
    'mw' 'jk' 'pe'...
    'ie' 'pw' 'ks' ...
    'mz' 'mm' 'ans'};

fs_ids = {'siobhan' 'avt' 'anthony_new_recon_2017'...
    'kalanit_new_recon_2017' 'mareike' 'jesse_new_recon_2017'...
    'brianna' 'swaroop' 'eshed'...
    'richard' 'cody' 'marisa'...
    'kari' 'alexis' 'nathan'...
    'dawn' 'erica' 'th'...
    'ek' 'gm' 'bl'...
    'mw' 'jk' 'pe'...
    'ie' 'pw' 'ks' ...
    'mz' 'mm' 'ans'};

RAID=['/sni-storage/kalanit/biac2/kgs'];

fsa_dir = fullfile(RAID, '3Danat', 'FreesurferSegmentations', 'fsaverage-bkup');

sessions={'01_sc_qMRI_080917' '02_at_qMRI_080517' '03_as_qMRI_083016'...
    '04_kg_qMRI_101014' '05_mg_qMRI_071217' '06_jg_qMRI_083016'...
    '07_bj_qMRI_081117' '08_sg_qMRI_081417' '10_em_qMRI_080817'...
    '12_rc_qMRI_080717' '13_cb_qMRI_081317' '15_mn_qMRI_111418'...
    '16_kw_qMRI_082117' '17_ad_qMRI_081817' '18_nc_qMRI_090817'...
    '19_df_qMRI_111218' '21_ew_qMRI_111618' '22_th_qMRI_112718'...
    '23_ek_qMRI_112918' '24_gm_qMRI_112818' '25_bl_qMRI_120718'...
    '26_mw_qMRI_032019' '27_jk_qMRI_032019' '28_pe_qMRI_040319'...
    '29_ie_qMRI_040319' '30_pw_qMRI_041219' '31_ks_qMRI_041019'...
    '32_mz_qMRI_041519' '33_mm_qMRI_041619' '34_ans_qMRI_041819'}

% avt kalanit swaroop

map_names = {'T1_map_Wlin'};

% loop through sessions and transform maps to fsaverage surfaces using CBA
for ss = 1:30
    anat_id = anat_ids{ss}; fs_id = fs_ids{ss}; ret_session = sessions{ss};
    % path to subject data in 3Danat
    anat_dir = fullfile(RAID, '3Danat', anat_id);
    % path to subject data in FreesurferSegmentations
    fs_dir = fullfile(RAID, '3Danat', 'FreesurferSegmentations', fs_id);
    % paths to subject mri and surf directories
    mri_dir = fullfile(fs_dir, 'mri'); surf_dir = fullfile(fs_dir, 'surf');
    % path to subject T1 session
    ret_dir = fullfile(RAID,'projects', 'NFA_tasks', 'data_mrAuto', ret_session);
    PredictDir = fullfile(RAID,'projects', 'PredictFuncFromStruct', 'data4Predict', strcat('Subject_',num2str(ss)));
    
    
    % generate parameter map files from mrVista parameter maps
    for mm = 1:length(map_names)
        map_name = map_names{mm}; % name of a mrVista parameter map file
        map_path = fullfile(ret_dir, 'mrQnew_processed' ,'OutPutFiles_1', 'BrainMaps', [map_name, '.nii.gz']);
        out_path = fullfile(PredictDir,'Volume', [map_name '.nii.gz']);
        cd(mri_dir);
        unix(['cp ' map_path ' ' fullfile(mri_dir, ['03_' map_name '.nii.gz'])]);
        cd(mri_dir);
        unix(['mri_convert -ns 1 -odt float -rt interpolate -rl orig.mgz ' map_path...
            ' ' fullfile(PredictDir,'Volume', ['03_' map_name '_resliced.nii.gz']) ' --conform']);
        
        
        % generate freesurfer-compatible surface files for each hemisphere
        % in GM
%         cd(surf_dir);
%         unix(['mri_vol2surf --mov ' fullfile(mri_dir, ['03_' map_name '_resliced.nii.gz']) ...
%             ' --reg register.dat --hemi lh --interp nearest --o ' ...
%             '03_' map_name '_lh_rescliced_proj0.mgh --projfrac 0']); % left hemi
%         unix(['mri_vol2surf --mov ' fullfile(mri_dir, ['03_' map_name '_resliced.nii.gz']) ...
%             ' --reg register.dat --hemi rh --interp nearest --o ' ...
%             '03_' map_name '_rh_rescliced_proj0.mgh --projfrac 0']); % right hemi
%         %         % transform surface files to fsaverage
%         map_stem = fullfile(fsa_dir, 'surf', ['03_' map_name]);
%         unix(['mri_surf2surf --srcsubject ' fs_id ' --srcsurfval ' ...
%             '03_' map_name '_lh_rescliced_proj0.mgh --trgsubject fsaverage-bkup --trgsurfval ' ...
%             map_stem '_lh_rescliced_proj0_regFrom_subj_' num2str(ss) '.mgh --hemi lh']); % left hemi
%         unix(['mri_surf2surf --srcsubject ' fs_id ' --srcsurfval ' ...
%             '03_' map_name '_rh_rescliced_proj0.mgh --trgsubject fsaverage-bkup --trgsurfval ' ...
%             map_stem '_rh_rescliced_proj0_regFrom_subj_' num2str(ss) '.mgh --hemi rh']);
%         
%         
        % generate freesurfer-compatible surface files for
        % each hemisphere in GM
        cd(surf_dir);
        
        proj_values=[0:0.1:1];
        for p=1:length(proj_values)
            
            unix(['mri_vol2surf --mov ' fullfile(PredictDir,'Volume', ['03_' map_name '_resliced.nii.gz']) ...
                ' --reg register.dat --hemi lh --interp nearest --o ' ...
                fullfile(PredictDir,'Surf',strcat('03_T1_in_GM_lh_proj_', num2str(proj_values(p)), '.mgh'))...
                ' --projfrac ' num2str(proj_values(p))]); % left hemi
            unix(['mri_vol2surf --mov ' fullfile(PredictDir,'Volume', ['03_' map_name '_resliced.nii.gz']) ...
                ' --reg register.dat --hemi rh --interp nearest --o ' ...
                fullfile(PredictDir,'Surf',strcat('03_T1_in_GM_rh_proj_', num2str(proj_values(p)), '.mgh'))...
                ' --projfrac ' num2str(proj_values(p))]); % left hemi
        end
        
        cd(fullfile(PredictDir,'Surf'));
        
        cmd_str=['rm ' strcat('03_T1_in_GM_lh_proj_mean.mgh')]
        system(cmd_str)
        cmd_str=['rm ' strcat('03_T1_in_GM_rh_proj_mean.mgh')]
        system(cmd_str)
        
        unix(['mri_concat --i ' strcat('03_T1_in_GM_lh_proj_*')...
            ' --o ' strcat('03_T1_in_GM_lh_proj_mean.mgh')...
            ' --mean']);
        unix(['mri_concat --i ' strcat('03_T1_in_GM_rh_proj_*')...
            ' --o ' strcat('03_T1_in_GM_rh_proj_mean.mgh')...
            ' --mean']);
        
        cd(surf_dir);
        proj_values=[-1:0.1:1];
        for p=1:length(proj_values)
            
            unix(['mri_vol2surf --mov ' fullfile(PredictDir,'Volume', ['03_' map_name '_resliced.nii.gz']) ...
                ' --reg register.dat --hemi lh --interp nearest --o ' ...
                fullfile(PredictDir,'Surf',strcat('03_T1_in_WM_lh_proj_', num2str(proj_values(p)), '.mgh'))...
                ' --projfrac ' num2str(proj_values(p))]); % left hemi
            unix(['mri_vol2surf --mov ' fullfile(PredictDir,'Volume', ['03_' map_name '_resliced.nii.gz']) ...
                ' --reg register.dat --hemi rh --interp nearest --o ' ...
                fullfile(PredictDir,'Surf',strcat('03_T1_in_WM_rh_proj_', num2str(proj_values(p)), '.mgh'))...
                ' --projfrac ' num2str(proj_values(p))]); % left hemi
        end
        
        cd(fullfile(PredictDir,'Surf'));
        
        cmd_str=['rm ' strcat('03_T1_in_WM_lh_proj_mean.mgh')]
        system(cmd_str)
        cmd_str=['rm ' strcat('03_T1_in_WM_rh_proj_mean.mgh')]
        system(cmd_str)
        
        
        unix(['mri_concat --i ' strcat('03_T1_in_WM_lh_proj_*')...
            ' --o ' strcat('03_T1_in_WM_lh_proj_mean.mgh')...
            ' --mean']);
        unix(['mri_concat --i ' strcat('03_T1_in_WM_rh_proj_*')...
            ' --o ' strcat('03_T1_in_WM_rh_proj_mean.mgh')...
            ' --mean']);
    end
end
