%% store paths to data directories and copy necessary files
% before this runs you need to copy the regsiter.dat file form
% FreesurferSegmentations/subject/labels to
% FreesurferSegmentations/subject/surf


anat_ids = {'siobhan' 'avt' 'anthony_new_recon_2017'...
    'kalanit_new_recon_2017' 'mareike' 'jesse_new_recon_2017'...
    'brianna' 'swaroop' 'eshed'...
    'richard' 'cody' 'marisa'...
    'kari' 'alexis' 'nathan'...
    'dawn' 'erica' 'th'...
    'ek' 'gm' 'bl'...
    'mw' 'jk' 'pe'...
    'ie' 'pw' 'ks' ...
    'mz' 'mm' 'ans'};

fs_ids = {'siobhan' 'avt' 'anthony_new_recon_2017'...
    'kalanit_new_recon_2017' 'mareike' 'jesse_new_recon_2017'...
    'brianna' 'swaroop' 'eshed'...
    'richard' 'cody' 'marisa'...
    'kari' 'alexis' 'nathan'...
    'dawn' 'erica' 'th'...
    'ek' 'gm' 'bl'...
    'mw' 'jk' 'pe'...
    'ie' 'pw' 'ks' ...
    'mz' 'mm' 'ans'};

 RAID=['/sni-storage/kalanit/biac2/kgs'];
 
fsa_dir = fullfile(RAID, '3Danat', 'FreesurferSegmentations', 'fsaverage-bkup');

% avt kalanit swaroop 

map_name = {'02_reading_vs_all_lh_proj_max'};

% loop through sessions and transform maps to fsaverage surfaces using CBA
for ss = 24:29
    anat_id = anat_ids{ss}; fs_id = fs_ids{ss};
    % path to subject data in 3Danat
    anat_dir = fullfile(RAID, '3Danat', anat_id);
    % path to subject data in FreesurferSegmentations
    fs_dir = fullfile(RAID, '3Danat', 'FreesurferSegmentations', fs_id);
    % paths to subject mri and surf directories
    mri_dir = fullfile(fs_dir, 'mri'); surf_dir = fullfile(fs_dir, 'surf');
    % path to subject retinotopy session
    map_dir = fullfile('/share/kalanit/biac2/kgs/projects/PredictFuncFromStruct/data4Predict',strcat('Subject_', num2str(ss)),'/Surf');
    outdir=fullfile('/share/kalanit/biac2/kgs/projects/PredictFuncFromStruct/data4Predict/fsaverageSpace');
    
    % transform surface files to fsaverage
    map_stem = fullfile(fsa_dir, 'surf', map_name);
    unix(['mri_surf2surf --srcsubject ' fs_id ' --srcsurfval ' ...
        fullfile(map_dir,strcat(map_name{:},'.mgh')) ' --trgsubject fsaverage-bkup --trgsurfval ' ...
        fullfile(outdir,strcat('Subject_',num2str(ss),'_',map_name{:},'.mgh')) ' --hemi lh']); % left hemi
end

