
fs_ids = {'siobhan' 'avt' 'anthony_new_recon_2017'...
    'kalanit_new_recon_2017' 'mareike' 'jesse_new_recon_2017'...
    'brianna' 'swaroop' 'eshed'...
    'richard' 'cody' 'marisa'...
    'kari' 'alexis' 'nathan'...
    'dawn' 'erica' 'th'...
    'ek' 'gm' 'bl'...
    'mw' 'jk' 'pe'...
    'ie' 'pw' 'ks' ...
    'mz' 'mm' 'ans'};

outDir=fullfile('/share/kalanit/biac2/kgs/projects/PredictFuncFromStruct/ScreenShots')
mkdir(outDir);
cd(outDir);

ROIs={'lh_OTS_anat'}
for s=[1,3,4,5,6,7,8,9]
for r=1:length(ROIs)
label_command = [':label=./label/aparc2009/predictFuncFromStructBoundaries/' strcat(ROIs{r},'.label') ':label_color=black:label_outline=1',...
        ':label=./label/aparc2009/predictFuncFromStructBoundaries/' strcat(ROIs{r},'_roi_Poly_new_readPredicted.label') ':label_color=green:label_outline=1'];
fs_loadFreeview(fs_ids{s},'lh','vl','02_reading_vs_all_lh_proj_max.mgh',0,[3,10],2,true,label_command)

end
end
% fs_load_freeview(subj, hemi, vw, map_name, nsmooth, thresh, zoom, screenshot)
% fs_load_freeview('fsaverage', 'lh', 'm', [], 1, [], 1.5, false)