%% store paths to data directories and copy necessary files
% before this runs you need to copy the regsiter.dat file form
% FreesurferSegmentations/subject/labels to
% FreesurferSegmentations/subject/surf


anat_ids = {'siobhan' 'avt' 'anthony_new_recon_2017'...
    'kalanit_new_recon_2017' 'mareike' 'jesse_new_recon_2017'...
    'brianna' 'swaroop' 'eshed'...
    'richard' 'cody' 'marisa'...
    'kari' 'alexis' 'nathan'...
    'dawn' 'erica' 'th'...
    'ek' 'gm' 'bl'...
    'mw' 'jk' 'pe'...
    'ie' 'pw' 'ks' ...
    'mz' 'mm' 'ans'};

fs_ids = {'siobhan' 'avt' 'anthony_new_recon_2017'...
    'kalanit_new_recon_2017' 'mareike' 'jesse_new_recon_2017'...
    'brianna' 'swaroop' 'eshed'...
    'richard' 'cody' 'marisa'...
    'kari' 'alexis' 'nathan'...
    'dawn' 'erica' 'th'...
    'ek' 'gm' 'bl'...
    'mw' 'jk' 'pe'...
    'ie' 'pw' 'ks' ...
    'mz' 'mm' 'ans'};

 RAID=['/sni-storage/kalanit/biac2/kgs'];
 
fsa_dir = fullfile(RAID, '3Danat', 'FreesurferSegmentations', 'fsaverage-bkup');

% avt kalanit swaroop 

map_name = {'Group_lh_OTS_union_morphing_reading_vs_all_proj_max_without_Subject_'};

% loop through sessions and transform maps to fsaverage surfaces using CBA
for ss = 1:30
    anat_id = anat_ids{ss}; fs_id = fs_ids{ss}; ret_session = sessions{ss};
    % path to subject data in 3Danat
    anat_dir = fullfile(RAID, '3Danat', anat_id);
    % path to subject data in FreesurferSegmentations
    fs_dir = fullfile(RAID, '3Danat', 'FreesurferSegmentations', fs_id);
    % paths to subject mri and surf directories
    mri_dir = fullfile(fs_dir, 'mri'); surf_dir = fullfile(fs_dir, 'surf');
    % path to subject retinotopy session
    in_dir=fullfile('/share/kalanit/biac2/kgs/projects/PredictFuncFromStruct/data4Predict/fsaverageSpace');
    out_dir = fullfile('/share/kalanit/biac2/kgs/projects/PredictFuncFromStruct/data4Predict',strcat('Subject_', num2str(ss)),'/ROIs');
    

    % transform surface files to fsaverage
        unix(['mri_surf2surf --srcsubject fsaverage-bkup --srcsurfval ' ...
            fullfile(in_dir,strcat(map_name{:},num2str(ss),'.mgh')) ' --trgsubject ' fs_id ' --trgsurfval ' ...
            fullfile(out_dir,strcat(map_name{:},num2str(ss),'.mgh')) ' --hemi lh --mapmethod nnf']); % left hemi
    end

